# Generated by Django 5.2 on 2025-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
